# Generated by Django 5.0.4 on 2024-05-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.AddField(
            model_name="film",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="film",
            name="genre",
            field=models.CharField(
                choices=[
                    ("Fiction", "Фантастика"),
                    ("Thriller", "Триллер"),
                    ("Roman", "Роман"),
                    ("Detective", "Детектив"),
                    ("Comedy", "Комендия"),
                ],
                default="Comedy",
                max_length=100,
                verbose_name="Жанр",
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="public_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата выпуска"),
        ),
        migrations.AddField(
            model_name="film",
            name="revenue",
            field=models.DecimalField(
                decimal_places=2, default="0.00", max_digits=10, verbose_name="Выручка"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="date_birth",
            field=models.DateField(default="2002-10-01", verbose_name="День рождения"),
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(default="", max_length=100, verbose_name="Имя"),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(default="", max_length=100, verbose_name="Фамилия"),
        ),
        migrations.AddField(
            model_name="user",
            name="patronynic",
            field=models.CharField(blank=True, max_length=100, verbose_name="Отчество"),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Телефон",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="position",
            field=models.CharField(
                choices=[
                    ("User", "Пользователь"),
                    ("Worker", "Сотрудник"),
                    ("Admin", "Админ"),
                ],
                default="User",
                max_length=100,
                verbose_name="Доступ",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Электронная почта"
            ),
        ),
    ]
