# Generated by Django 5.0.4 on 2024-05-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_remove_user_name_film_description_film_genre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="photos/%y/%m/%d/", verbose_name="Фото"
            ),
        ),
    ]
